version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: esprithub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: esprithub
      POSTGRES_USER: esprithub_user
      POSTGRES_PASSWORD: esprithub_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - esprithub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esprithub_user -d esprithub"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: esprithub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - esprithub-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: esprithub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@esprit.tn
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - esprithub-network

volumes:
  postgres_data:

networks:
  esprithub-network:
    driver: bridge
